### ISSUE TITLE
Dependency check symfony/cache and symfony/console

### ISSUE THREAD

**Issue by blood72** [dolejska-daniel/riot-api-datadragon#2]
**Is your feature request related to a problem? Please describe.**
In Laravel 9, the dependence of `symfony/console` and `symfony/cache` increased to ^6.

**Describe the solution you'd like**
I think just need to add support for that version from the `composer.json`.
```json
	"require": {
		"symfony/console": "^6|^5",
		"symfony/cache": "^6|^5",
	},
```

**Describe alternatives you've considered**
It would be nice to check if the `symfony/console` package is actually being used in the DataDragon library.
As far as I remember, version 4 provided the CLI.
If it is not used on the code and is unnecessary, you can consider deleting it.

**Additional context**

**Comment by dolejska-daniel** [comment]
Hello! I'm just in the middle of refactoring the base code to PHP8.1. Updated symfony dependencies will be included!

https://github.com/dolejska-daniel/riot-api-base/pull/5

**Comment by funforgiven** [comment]
Any updates?

**Comment by katerlol** [comment]
Would also be curious for an update. 👀

**Comment by DigitalChaosNL** [comment]
I guess this package is not maintained anymore? Symfony 7.0 will be released at the end of this year.

**Comment by TheMY3** [comment]
Hope so, waiting for this update too.

**Comment by dolejska-daniel** [comment]
Sorry guys, for the wait. I am so glad you are still using this and (_maybe_) enjoying it. I hope this update will help you achieve what you need. **However, this is one of the last updates that I will be able to deliver** since I lost my interest in League over the last few years; Hence, this set of libraries is currently looking for a new enthusiastic maintainer 😸
